sudo: false
language: node_js
node_js:
  - 12.14.1 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
before_install:
- cd blog;
- git config --global user.name "mmfei"
- git config --global user.email "wlfkongl@163.com"
- sed -i'' "s~https://github.com/xgoteam/manuals_for_it_developers.git~https://${ACCESS_TOKEN}@github.com/xgoteam/manuals_for_it_developers.git~" _config.yml

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-filter-mermaid-diagrams --save
- npm install hexo-renderer-sass --save
- npm install https://github.com/CodeFalling/hexo-asset-image --save
- npm install hexo-hrefmd --save

# before_script: cd blog
script:
  - hexo clean
  - hexo generate # generate static files
  - npm run deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: blog/public